version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bmtc-mcp-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/bmtc-mcp
      - REDIS_URI=redis://redis:6379
      - API_KEY=your_api_key_here
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRES_IN=86400
      - BMTC_API_ENDPOINT=https://bmtc-api-endpoint.example
      - BMTC_API_KEY=your_bmtc_api_key_here
      - CACHE_DURATION=300
      - LOG_LEVEL=info

  mongo:
    image: mongo:6
    container_name: bmtc-mcp-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: bmtc-mcp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
